/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ApontamentoRouteImport } from './routes/apontamento'
import { Route as IndexRouteImport } from './routes/index'

const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApontamentoRoute = ApontamentoRouteImport.update({
  id: '/apontamento',
  path: '/apontamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apontamento': typeof ApontamentoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apontamento': typeof ApontamentoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apontamento': typeof ApontamentoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apontamento' | '/checklist' | '/configuracoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apontamento' | '/checklist' | '/configuracoes'
  id: '__root__' | '/' | '/apontamento' | '/checklist' | '/configuracoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApontamentoRoute: typeof ApontamentoRoute
  ChecklistRoute: typeof ChecklistRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apontamento': {
      id: '/apontamento'
      path: '/apontamento'
      fullPath: '/apontamento'
      preLoaderRoute: typeof ApontamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApontamentoRoute: ApontamentoRoute,
  ChecklistRoute: ChecklistRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
